### ISSUE TITLE
LCD going off after some time / when under a specific Temperature

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [atc1441/ATC_MiThermometer#11] opened 2020-09-05 17:06 UTC
Hi,

I try to flash LYWSD03MMC with following firmware: ATC_Thermometer_custom.bin. However after some time (like 60 seconds) LCD is going off - it is still possible to connect/send firmware using TelinkFlasher.

With ATC_Thermometer LCD is on only on "bootup" process then it goes off and doesn't show temperature.

With stock firmware LCD is on and shows temperature all the time...

Please advise.

Best Regards

**Comment by atc1441** [comment] 2020-09-05 17:41
Hey, it seems @leahneukirchen also hat that problem with one Thermometer,

did you try to reinsert the battery? 

there is one unknown pin goin to the lcd controller and it may have something to do with that.

my devices all work fine so its hard for me to debug

**Comment by leahneukirchen** [comment] 2020-09-05 17:48
I have one running your firmware, which went out in the freezer and came back fine later.

I have one running on stock firmware again which shows this behavior, it went out after 5-30s with your firmware after power cycling.

In general, power cycling made the display work again, but then it went off with the latter one again.

**Comment by atc1441** [comment] 2020-09-05 17:57
Do any one of you may have the possibility to open one ? 

that way its could be compared against the other ones to see if they are a different revision

**Comment by leahneukirchen** [comment] 2020-09-05 18:05
I need to find such a small torx, maybe I have one at work. Gonna take a few days.

I ordered both in the same shipment, I can compare the numbers on the back next wekk.

**Comment by 6Xkljk8Vj7Tk1k4** [comment] 2020-09-05 18:35
I took few more from my order and they work as expected. I had a problem with one more, however after turn off and on again it shown temperature. Anyway the first one is still off, switching on/off, reflash or battery replace didnt help. 
[board1](https://ibb.co/7Vpm7Hp)
[board2](https://ibb.co/4WfdY12)

[:)](https://ibb.co/yWgCWrq)

**Comment by atc1441** [comment] 2020-09-05 18:52
Thank you for the images. My boards are exactly the same.

Must be something else

**Comment by benek984** [comment] 2020-09-05 20:18
I have flashed my 14 sensors and all are experience that same issue. After several minutes screen freeze and doesn't display current temperature correctly. Power cycle fixing the issue but just for a another several minutes. I haven't have this problem on the stock firmware.

**Comment by bbbenji** [comment] 2020-09-06 14:41
I flashed 4 of my sensors, and one of them is experiencing the aforementioned screen blanking. Reinserting the battery fixes it, but only temporarily. It may have to do with the fact I use that one in the fridge as I pulled it out this morning and it hasn't blanked yet. I will swap it with another and see if I can replicate the issue.

**Comment by benek984** [comment] 2020-09-06 15:47
I have flashed my 14 sensors again this morning using the latest .bin file. After flashing I set them to as follow:
Smiley: OFF
Advertising Type: Mi Like
Show battery in LCD: Disabled
Advertising interval: 10 Seconds 

So far all good, sensors doesn't freeze anymore and reporting back to my Home Assistant by connecting via ESPHome BLE_tracker and xiaomi_cgg1 platform.

example of my configuration:

esp32_ble_tracker:
sensor:  
  - platform: xiaomi_cgg1
    mac_address: "A4:C1:38:BD:89:4E"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Battery Level"

**Comment by bbbenji** [comment] 2020-09-06 15:51
Reporting back that the thermometer that was working fine for days now, blanked after 30min of being in the fridge. I suspect it has to do with low temperatures. Will try another thermometer.

**Comment by benek984** [comment] 2020-09-06 16:00
> Reporting back that the thermometer that was working fine for days now, blanked after 30min of being in the fridge. I suspect it has to do with low temperatures. Will try another thermometer.

try my settings:

Smiley: OFF
Show battery in LCD: Disabled

This prevent sensor on blinking between two screens (battery or humidity) in my case those settings have solved the issue.

**Comment by bbbenji** [comment] 2020-09-07 17:20
@benek984 Unfortunately those settings did not help. I can quite consistency reproduce the screen blanking by placing any of my 4 thermometers in the fridge. Need to try using ATC format, using Mi at the moment.

**Comment by atc1441** [comment] 2020-09-07 18:44
@bbbenji ok the not showing of data on the lcd when in freezer is also same for me. Havent tested that with stock firmware but i think that is display related. If i press on the lcd when in freezer it comes back while pressing it. 

Dies this work as well?

**Comment by bbbenji** [comment] 2020-09-07 19:25
Pressing the screen does not do anything for me. Sounds like a hardware issue. However, my fridge is approx. +6 degrees  celsius, well within the spec'ed range. I have not tested stock firmware yet.

**Comment by atc1441** [comment] 2020-09-08 09:23
Tested a bit further, Stock vs. Custom rom in freezer, the display of the Stock rom stays on the custom not
![20200908_111931](https://user-images.githubusercontent.com/1102694/92458362-90e50180-f1c5-11ea-9bee-377149e41664.jpg)

Hard to do an i2c capture while in freezer, i could imagine they set the voltage of the lcd controller higher when under a specific °C

**Comment by atc1441** [comment] 2020-09-08 10:01
Looking further onto the PCB i following the unknown pin i already mentioned and will try to capture if that one has something to do with it.

![20200908_115524](https://user-images.githubusercontent.com/1102694/92462609-fc7d9d80-f1ca-11ea-9f42-6d6647f9c2e3.jpg)

**Comment by atc1441** [comment] 2020-09-08 11:08
![20200908_130408](https://user-images.githubusercontent.com/1102694/92468884-2ab3ab00-f1d4-11ea-8052-9cff466b21ac.jpg)

Good news, setting that pin (PB6) to a level and not leaving it floating fixed the issue :)
https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer/main.c#L30

Its already updated in the repo and can be flashed.

**Comment by nikito7** [comment] 2020-09-09 13:47
Still an issue at 26° on one sensor

**Comment by atc1441** [comment] 2020-09-09 13:52
Thank you for the info. 
Is it instant off after inserting the battery or how is the behavior?

**Comment by nikito7** [comment] 2020-09-09 14:25
After new flash. When I connect
I waiting 60s its ok, then connect with flasher turn off.

Maybe related with some ble discovery

Because now, after insert battery, goes off 10-20s after

**Comment by nikito7** [comment] 2020-09-09 14:43
Now after blink one time
28°
Maybe temperature related.

I flashed stock again, and then custom, I never reached the 60s in first time

**Comment by nikito7** [comment] 2020-09-09 14:50
At 17°C works fine....

**Comment by leahneukirchen** [comment] 2020-09-09 18:39
I flashed the firmware of HEAD on the Mi that went dark quickly, and it turns off immediately after the MAC now... Bluetooth works fine.

I also opened it and wiggled the LCD connector a bit, but I think that is not the issue, as it displays fine in the begining.

(Display was fine with the stock firmware, too.)

**Comment by nikito7** [comment] 2020-09-09 18:49
Maybe are clones
I have one with a "very soft purple" background lcd

**Comment by leahneukirchen** [comment] 2020-09-09 18:55
Indeed, the LCD colors are different. The working one is "very soft purple", the non-working one is "dark greenish".

**Comment by nikito7** [comment] 2020-09-09 18:59
The problem is above 20°C

It's working at -10°C (-9.9 on lcd)

Cold kills battery fast :)

**Comment by leahneukirchen** [comment] 2020-09-09 19:00
It was only cold for a few minutes. But we have 20°C inside, so....

**Comment by nikito7** [comment] 2020-09-09 19:04
Maybe less

Put in freezer, remove/reinsert the battery less 15° because hot hands

My works that way. If I take it out freezer. Go blank after a while

**Comment by leahneukirchen** [comment] 2020-09-09 19:28
Powercycled it at 11.8°C, display came back; warmed up in ~15min to 20°C. Still on.. let's see.

**Comment by leahneukirchen** [comment] 2020-09-09 19:29
Went out at ~20.5°C again. :(

**Comment by nikito7** [comment] 2020-09-09 19:33
Maybe is the Humidity...

21.3°C 78% still on

**Comment by leahneukirchen** [comment] 2020-09-09 19:39
Humidity fell to 60%.

**Comment by atc1441** [comment] 2020-09-09 19:48
I could also imagine that the display needs to be set into a different mode on different temperatures. So like pull pin low on low temp and high on high temp. 

A reinit of the lcd is needed after setting a different level on that pin. But that shouldnt be a problem to do.

To bad there is no info on the lcd controller

**Comment by atc1441** [comment] 2020-09-09 19:49
On mine i had only problems on very low temp so far maybe someone can upload an comparison of the two lcds in one picture

**Comment by leahneukirchen** [comment] 2020-09-09 19:55
Perhaps expose the pin over bluetooth so we noobs can toggle it over the browser. :)

**Comment by nikito7** [comment] 2020-09-09 19:58
10s broadcast maybe faulty

the event:
![20200909_205456](https://user-images.githubusercontent.com/45373783/92647077-39d34f80-f2df-11ea-8e82-32b8f799d47b.jpg)

**Comment by atc1441** [comment] 2020-09-09 20:07
@leahneukirchen only toggle would help to much as the init is needed. So needed compine that somehow first :-/

@nikito7 can you explain that a bit more? 
I can imagine that the newly added alarm do somethong wrong there, it will do an instant advertise if the Temp or Humi changes more than 0.5C / 5% between a main loop delay (5-6 seconds), there is a bug in it that will advertise twice if in the same loop a timed advertising was happening. 
Will change that

**Comment by atc1441** [comment] 2020-09-09 20:14
@nikito7  fixed that particular bug right now

**Comment by nikito7** [comment] 2020-09-09 20:19
chart was for lcd off event

**Comment by nikito7** [comment] 2020-09-09 20:30
Your change fixed LCD issue

**Comment by atc1441** [comment] 2020-09-09 20:32
Yeah should not fixed that one. Only changed the instant advertising. 

Will look deeper into what the stock firmware is doing with the pin. Maybe even capture some data while im freezer with a wire to a logic analyzer or something.

**Comment by nikito7** [comment] 2020-09-09 20:39
Can you confirm that 10s broadcast is working?

If working. Esphome or homeassistant is filtering data

**Comment by atc1441** [comment] 2020-09-09 20:45
@nikito7 yes can confirm that it does work at 10s interval just tested it again. Its 10-15 Seconds to be precise as its only tested for the interval if the main loop interval was overflowed as well.

There is a problem with interval bigger than 3minutes but that will be fixed later.

**Comment by Calcu2006** [comment] 2020-09-10 23:11
Hi benek984

I did everything like you, but maybe i'm forgetting something... i can read the values in MQTT.. can you please put an example about how are you reading it?

I created this sensor:
  - platform: mqtt
    name: "testing pc"
    state_topic: "esp_entrada/sensor/temperatura_ordenador/state"
    unit_of_measurement: "°C"

but status is always unknown..., what i'm missing ?

Thanks for answering!

> 
> 
> I have flashed my 14 sensors again this morning using the latest .bin file. After flashing I set them to as follow:
> Smiley: OFF
> Advertising Type: Mi Like
> Show battery in LCD: Disabled
> Advertising interval: 10 Seconds
> 
> So far all good, sensors doesn't freeze anymore and reporting back to my Home Assistant by connecting via ESPHome BLE_tracker and xiaomi_cgg1 platform.
> 
> example of my configuration:
> 
> esp32_ble_tracker:
> sensor:
> 
>     * platform: xiaomi_cgg1
>       mac_address: "A4:C1:38:BD:89:4E"
>       temperature:
>       name: "Bedroom Temperature"
>       humidity:
>       name: "Bedroom Humidity"
>       battery_level:
>       name: "Bedroom Battery Level"

**Comment by nikito7** [comment] 2020-09-10 23:22
> Hi benek984
> 
> I did everything like you, but maybe i'm forgetting something... i can read the values in MQTT.. can you please put an example about how are you reading it?
> 
> I created this sensor:
> 
> * platform: mqtt
>   name: "testing pc"
>   state_topic: "esp_entrada/sensor/temperatura_ordenador/state"
>   unit_of_measurement: "°C"
> 
> but status is always unknown..., what i'm missing ?
> 
> Thanks for answering!

Use api in esphome.yaml

api:
    password: pass

And add integration "esphome" in homeassistant

**Comment by benek984** [comment] 2020-09-11 08:54
Hi Calcu2006,

I use ESPHome plugin with Home Assistant, to read values from sensors I have ESP32 board with ESPHome on board. 
As mentioned by nikito7 this will autodiscover sensors added to the ESP32 config so you don't need to edit your yaml config file in home assistant. 
Example config below:

esphome:
  name: esp32_ble_01
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "xxxx"
  password: "xxx"
  power_save_mode: none
  use_address: 192.168.10.135
  

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxx"
    password: "xxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API

api:
  password: "xxx"

ota:
  password: "xxx"
  
web_server:

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
      
  - platform: xiaomi_lywsd03mmc
    bindkey: "26d11deb1fcfae7862a462839a5156a9"  ----- "This is fake value but is necessary for that platform, you can use diffrent xiaomi platform from ESPHome but I found this one the most stable for those sensors". 

    mac_address: "aa:aa:aa:aa:aa:aa"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Batery Level"

**Comment by Calcu2006** [comment] 2020-09-11 09:21
Thanks, i was creating MQtt sensors... now everything works, thanks again !

**Comment by rnizametdinov** [comment] 2020-09-15 15:59
Same issue - revert to stock firmware

**Comment by giannoug** [comment] 2020-09-16 10:12
Same issue here. Right after flashing, the boot screen appears (showing "Atc", happy face and mac), then screen turns off. This is what happens all of the time, but it stayed a couple of seconds in the temperature / humidity screen once.

**Comment by atc1441** [comment] 2020-09-16 21:46
I compiled a version now where it pulls the LCD pin high and not low, maybe someone who has the error can flash it and test it, that way we would know if looking into that direction would help.
especially @rnizametdinov  and @giannoug 

[ATC_Thermometer_LCD_HIGH.zip](https://github.com/atc1441/ATC_MiThermometer/files/5235115/ATC_Thermometer_LCD_HIGH.zip)

**Comment by giannoug** [comment] 2020-09-16 21:55
@atc1441 Just flashed `ATC_Thermometer_LCD_HIGH.bin`. Doesn't seem to fix the issue. It goes to blank screen straight after booting

**Comment by atc1441** [comment] 2020-09-16 21:59
Thank you for testing it. Looks like its still a different error.

Are the other ones from you working fine?

**Comment by giannoug** [comment] 2020-09-16 22:06
@atc1441 What other ones are you referring to? I don't have other devices available and the stock firmware works fine (both the one that came from the manufacturer and the one you provide in the README)

**Comment by atc1441** [comment] 2020-09-16 22:07
Thought you maybe bought a pack of four or something. 

But no problem :)

**Comment by nikito7** [comment] 2020-09-16 22:29
The good ones have lcd issue now
Dont update :p

**Comment by atc1441** [comment] 2020-09-17 05:05
@nikito7 yes that was just for the bad ones as a test :)

Will delete the file now.

**Comment by rnizametdinov** [comment] 2020-09-17 13:15
> especially @rnizametdinov and @giannoug
> Edit. File deleted to prevent miss flashes
I have 3 thermometer.
2 of them - turn off screen on this firmware. 
And last one - work 3 hours and everything OK. 
I tray change battery between them - everything same: first 2 screen off, last one - work fine.
I will tray open them and find differense.

**Comment by atc1441** [comment] 2020-09-17 13:37
Thank you

**Comment by rnizametdinov** [comment] 2020-09-17 19:58
> Thank you

![PXL_20200917_184933368](https://user-images.githubusercontent.com/9716071/93521333-931f2c80-f938-11ea-94fd-b7debc3dcfea.jpg)
![PXL_20200917_185200865](https://user-images.githubusercontent.com/9716071/93521351-9b776780-f938-11ea-9fab-bb15d679ad17.jpg)

Left - turn off screen. As I can see - they are the same :(. 
I try use good motherboard with "bad" display - work well. 
I try use bad motherboard with "good" display -  don'twork. 
On motherboard I see two connection roads from main controller to display controller - is it use i2c for display control?

**Comment by nikito7** [comment] 2020-09-17 20:04
Why chip numbers change?

![20200917_205634](https://user-images.githubusercontent.com/45373783/93522463-69123e00-f929-11ea-85db-0e128cf7978c.jpg)
![20200917_205643](https://user-images.githubusercontent.com/45373783/93522468-6b749800-f929-11ea-9598-2311b5a50cec.jpg)
![20200917_205749](https://user-images.githubusercontent.com/45373783/93522472-6c0d2e80-f929-11ea-8e4e-a9a557a38b95.jpg)
![20200917_205755](https://user-images.githubusercontent.com/45373783/93522478-6d3e5b80-f929-11ea-9808-4a0eb855fdb3.jpg)

**Comment by atc1441** [comment] 2020-09-17 20:08
Thank you for the in depth pictures, it seems like they changed something in the LCD controller ic then, 

All my have the F200 version. and they work fine

**Comment by nikito7** [comment] 2020-09-17 20:12
33 work
3E not

**Comment by nikito7** [comment] 2020-09-17 20:25
I swapped lcd too, and... the lcd is not the problem

**Comment by atc1441** [comment] 2020-09-17 20:27
Yes it will be the lcd controller as this is the only thing different.
Will order one more and with luck i get a bad one that i can use to debug it

**Comment by nikito7** [comment] 2020-09-17 20:29
Four digits, its the time I think (board itself, chips, etc)

**Comment by giannoug** [comment] 2020-09-20 13:53
@atc1441 Yes I got a lot of them, but only had one available when I tested! I've tried 2 more but it seems they both have the new LCD controller and aren't working.

Can you share some information about how are you going to reverse engineer them? If I understood correctly, the LCD is using an I2C bus. Will an Arduino-based I2C sniffer work? I might be able to get some packets out of them

**Comment by atc1441** [comment] 2020-09-20 14:07
Understand,

the reversing is done with a mix of I2C Sniffing and looking into the Stock firmware with Ghidra

The communication is so far only in one direction so from the MCU to the LCD Controller.

I just got the idea that maybe the unknown GPIO could be a signal from the LCD Controller to the MCU and not in the other direction, need to test that, maybe by cutting the trace to see from where the voltage comes.

Also the Stock firmware is the same for both variants so its can not really be an I2C cmd as there is only writing and no reading as mentioned

**Comment by nikito7** [comment] 2020-09-20 14:07
Can you auto detect chip on code?
This may be need to be dynamic.
Because xiaomi firmware is just one for all

**Comment by atc1441** [comment] 2020-09-20 14:17
Yes that would definitely be the plan, but for that we first need to know what is wrong :)

**Comment by giannoug** [comment] 2020-09-20 14:20
@atc1441 But why is the LCD working on boot and then stops? I can see the boot screening showing "Atc" along with the last 2 chars of the mac and it then stops. Isn't the boot screen controlled by the same code?

**Comment by atc1441** [comment] 2020-09-20 14:23
I think that has something todo with the retention. 
The cpu goes to sleep all the time and on wakeup it is like a reset. That is happening between the ATC and the temp. I can not really debug what its wrong there without a non working device otherwise i would test stuff

**Comment by giannoug** [comment] 2020-09-20 14:25
I can see the bootscreen when I insert the battery, if that helps. It dies exactly before showing the main screen.

**Comment by nikito7** [comment] 2020-09-20 14:44
Can we use a voltimeter on lcd pins?

**Comment by atc1441** [comment] 2020-09-20 14:49
Yes not problem with voltmeter,

Cou can cut the trace between the lcd controller and thermometer and meassure both side what level they have.

See the image i posted earlier about the trace

**Comment by ralf-e** [comment] 2020-09-20 19:20
> I think that has something todo with the retention.
> The cpu goes to sleep all the time and on wakeup it is like a reset. That is happening between the ATC and the temp. I can not really debug what its wrong there without a non working device otherwise i would test stuff

Here I have two with LCD controllers
IST3055NAO
RBTNN700
2013
one of them freezes
most of the others are ... R200, so no problems with those.
Should I send you the "Freezer" to try out? If so, address?

![IMG_20200920_210622__01](https://user-images.githubusercontent.com/3521615/93720061-f56d6c80-fb86-11ea-856c-7e2877481cc6.jpg)

**Comment by atc1441** [comment] 2020-09-20 19:26
Just send you a mail. 
Would be very kind of you!

**Comment by ralf-e** [comment] 2020-09-20 20:33
Goes on the way tomorrow..

**Comment by atc1441** [comment] 2020-10-02 18:42
@ralf-e  I got the Thermometer from you, 

I played around with it to see where the problem is and tested different things, right now it still is not solved as i had not too much time.

but just so you know

**Comment by atc1441** [comment] 2020-10-02 18:58
Ok, played a bit more and with the Osci it was now quite obvious what the reason is.


the pin needs to be pulled HIGH on boot that will be perfectly done but the moment the TLSR goes to sleep the GPIO will be reset and low again, 

the goal is now to enable the GPIO B6 even when in sleep mode. 

Nice to see the reason

**Comment by atc1441** [comment] 2020-10-02 19:23
IT IS FIXED :)

Setting it to a pullup level keeps it high during sleep. 

For me all the devices i have work that way. 

Please try it out, the newest version is online and ready to be flashed

**Comment by giannoug** [comment] 2020-10-02 19:33
Yeap, just flashed it and it works! Good job!

**Comment by atc1441** [comment] 2020-10-02 19:41
Nice to hear that it works for you as well, i am quite confident that this is the solution :)

**Comment by ralf-e** [comment] 2020-10-03 07:37
> I played around with it to see where the problem is and tested different things, right now it still is not solved as i had not too much time.

one of my parts has the identical LCD controller version as the thermometer I sent you. Here the error only occurs every few days. Can it possibly only be a question of timing problems with the connection between the LCD controller and MCU (component variation)?

**Comment by atc1441** [comment] 2020-10-03 08:02
I looked at what the stock firmware does and it pulls the pin HIGH.

For now my firmware did only pull it low as HIGH did not work becuse of the sleep reset. At that point i hadnt looked into it with the osci.

It is pulled high as in the stock firmware and i am very shure it will help

As the firmware is the same for all versions and the mcu does not know what lcd controller is connected it can not behaiv different on other lcd controllers

**Comment by rnizametdinov** [comment] 2020-10-03 11:32
Upload new firmware on three my device - work fine. Awesome job!
After upload humidity drop a little, dont matter for me (I monitor difference between main room and bathroom)
p.s atc1441 , can you compile fw with "mi like" broadcast by default? So we choose "ATC_Thermometer.bin" or "ATC_Thermometer_Mi_like.bin" ?
Now we must change "mi like" after every battery out\insert.
![2020-10-03_14-22-15](https://user-images.githubusercontent.com/9716071/94990335-f2f61400-0583-11eb-8781-608247f84665.png)
![image](https://user-images.githubusercontent.com/9716071/94990372-3486bf00-0584-11eb-9310-4f58d35a0055.png)

**Comment by atc1441** [comment] 2020-10-03 11:37
A precompiled version with mi like is definitely an option.
But that gives another problem, i have to recompile every update for both versions and test them. I want to avoid that.

My other plan was to make it save the values in flash so they dont get lost.

**Comment by giannoug** [comment] 2020-10-03 11:39
@atc1441 Take a look into GitHub Actions and Releases. You can have it compile FW for you automatically on every push and add a release in the Releases page

**Comment by nikito7** [comment] 2020-10-03 11:58
> After upload humidity drop a little, dont matter for me (I monitor difference between main room and bathroom)

Send FB05 setting

**Comment by yorickvP** [comment] 2020-10-03 12:02
It's weird that the humidity went down. Does this change significantly impact power draw?

**Comment by giannoug** [comment] 2020-10-03 12:06
Humidity went down for me too for all sensors after flashing

![image](https://user-images.githubusercontent.com/509474/94991178-01dfc500-058a-11eb-8bc5-0f0b6845675a.png)

**Comment by atc1441** [comment] 2020-10-03 12:06
i could imagine that the humidity went down because while flashing the SOC is on the hole time an drains the battery but only while flashing so now the battery is a bit lower than usual, and maybe also because the thermometer was touched, dont know if it was just done OTA

Both is just a guess.


@giannoug i dont trust Github Actions for that part. i always want to make shure that everything works on a real flashed device.
i know you only want to help :)

**Comment by atc1441** [comment] 2020-10-03 12:10
Lets see if they recovery in about 3 hours or so and if not i will investigate further. i only changed something in the removing of the Mi id and the Pullup resistor.

another thing to test would be to flash the old firmware and see if its up again

**Comment by nikito7** [comment] 2020-10-03 12:11
stock firmware maybe had a default offset.
I always send FB05, always... and click mi-like :-)

**Comment by atc1441** [comment] 2020-10-03 12:12
Yes from Stock to Custom is about 5% difference, but what is strange is that its flashed from Custom to new Custom

**Comment by nikito7** [comment] 2020-10-03 12:17
Charts are ok here. He need FB05 after flash.
Or is something else

**Comment by rnizametdinov** [comment] 2020-10-03 19:55
> Yes from Stock to Custom is about 5% difference, but what is strange is that its flashed from Custom to new Custom

 I flash from stock to custom, and have stable  5% Hum drop.
@nikito7 thanks for advice. 


> My other plan was to make it save the values in flash so they dont get lost.

It will be awesome!

**Comment by atc1441** [comment] 2020-10-03 20:05
Ok the 5% drop it totally fine then.

Thought you where already on stock before

**Closed** 2020-11-12 03:11 UTC
